theme = "blowfish"
baseURL = "https://marcgelpi.com/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
summaryLength = 30
disableKinds = ["taxonomy", "term"]

[pagination]
  pagerSize = 10

[imaging]
  anchor = "Center"

[caches]
  [caches.images]
    dir = ":cacheDir/images"

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[outputs]
  home = ["HTML", "RSS"]
