#!/usr/bin/env bash

acceptance_browser_assert_release_metadata() {
  local description=$1
  local public_paths_json=$2
  local article_paths_json=$3

  acceptance_browser_assert_eval \
    "$description" \
    "(async () => { const paths = $public_paths_json; const articlePaths = new Set($article_paths_json); const articlePath = '/writing/life-isnt-always-a-river/'; const articleSearchDescription = 'A changed product decision is not automatically a bad one. See how visible reasoning helps teams distinguish learning from chaos.'; const articleSocialDescription = 'Product decisions change. That doesn’t always mean they were wrong.'; const pageOverrides = new Map([['/', { socialTitle: 'Marc Gelpí', socialDescription: 'People-first organizational effectiveness and ways of working.' }], ['/about/', { type: 'profile' }], [articlePath, { searchDescription: articleSearchDescription, socialDescription: articleSocialDescription }]]); const pages = await Promise.all(paths.map(async path => { const response = await fetch(path); const html = await response.text(); const doc = new DOMParser().parseFromString(html, 'text/html'); const meta = key => Array.from(doc.querySelectorAll('meta')).find(node => node.getAttribute('name') === key || node.getAttribute('property') === key)?.content; return { path, ok: response.ok, lang: doc.documentElement.lang, title: doc.title, description: meta('description'), canonical: doc.querySelector('link[rel=\"canonical\"]')?.href, ogTitle: meta('og:title'), ogDescription: meta('og:description'), ogUrl: meta('og:url'), ogType: meta('og:type'), ogLocale: meta('og:locale'), ogImage: meta('og:image'), twitterCard: meta('twitter:card'), twitterDescription: meta('twitter:description') }; })); const uniqueTitles = new Set(pages.map(page => page.title)).size === pages.length; const uniqueDescriptions = new Set(pages.map(page => page.description)).size === pages.length; const accurate = pages.every(page => { const expectations = { type: articlePaths.has(page.path) ? 'article' : 'website', socialTitle: page.title, socialDescription: page.description, searchDescription: page.description, ...pageOverrides.get(page.path) }; return page.ok && page.lang === 'en' && page.title && page.description === expectations.searchDescription && page.canonical === 'https://marcgelpi.com' + page.path && page.ogTitle === expectations.socialTitle && page.ogDescription === expectations.socialDescription && page.twitterDescription === expectations.socialDescription && page.ogUrl === page.canonical && page.ogType === expectations.type && page.ogLocale === 'en_GB' && page.ogImage?.startsWith('https://marcgelpi.com/') && page.twitterCard === 'summary_large_image'; }); return uniqueTitles && uniqueDescriptions && accurate; })()" \
    "true"
}
